### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by Rounak-Saha13** [Yogndrr/MERN-School-Management-System#3]
MongoDB is not getting connected in the sample code

**Comment by bloater01** [comment]
![image](https://github.com/Yogndrr/MERN-School-Management-System/assets/134257050/e7a73bff-7e01-4d0f-aecc-7a78fb3facae)

**Comment by nalinrajendran** [comment]
Create a .env file and create a MONGO_URL parameter and add a mongoDB URI there in the backend. Also uncomment the .env in the frontend

**Comment by bhavy52** [comment]
when singing up as admin the box just reloads and nothing happens

**Comment by maiemy20** [comment]
> Create a .env file and create a MONGO_URL parameter and add a mongoDB URI there in the backend. Also uncomment the .env in the frontend

Can you explain more?

**Comment by Shiva0krishna** [comment]
@maiemy20    Bro, Just create file  named  .env in the  backend folder and  add     MONGO_URL=mongodb://localhost:27017/         this  in it .And   .env  file in frontend folder is in commented ,just uncomment it .so that  it can be accesed by components. By the way Thanks  to @nalinrajendran and @Yogndrr

**Comment by sivaprasanth2221** [comment]
i could not signup as admin and it is kept on loading.

**Comment by nalinrajendran** [comment]
Use the create admin function manually

**Comment by Yogndrr** [comment]
If it is still giving you an error then we can have a meet call where I can
solve that problem for you... Reply me with a google meet link if you want
to solve it.

**Comment by albin2771git** [comment]
showing network error, while login or register,

**Comment by Allan-Kipkemei** [comment]
I receive the same error

**Comment by OladitiSamuel** [comment]
Connected to MongoDB
Server started at port no. 5000
NOT CONNECTED TO NETWORK MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
 
Here is the error I got

**Comment by sivaprasanth2221** [comment]
Just change the port no and run again. Also create an .env file in the backend. Make sure that you have the same port no of backend in the .env file of the frontend.

**Comment by Yogndrr** [comment]
To fix this go to the backend, 
Create a file called .env in the backend folder.
Inside it write this :

MONGO_URL = mongodb://127.0.0.1/school

Instead of this link write your database link. 

Now in frontend go to src > redux > userRelated > userHandle.js

Write this after the import statements :

const REACT_APP_BASE_URL = "http://localhost:5000"

Now replace all process.env.REACT_APP_BASE_URL with REACT_APP_BASE_URL.

The problem here was that the .env file in the frontend was not working for other users while it works for me.
So you have to do this in the frontend. After this the project will run smoothly if not then you can contact me.

**Comment by Yogndrr** [comment]
> I receive the same error

To fix this go to the backend, 
Create a file called .env in the backend folder.
Inside it write this :

MONGO_URL = mongodb://127.0.0.1/school

Instead of this link write your database link. 

Now in frontend go to src > redux > userRelated > userHandle.js

Write this after the import statements :

const REACT_APP_BASE_URL = "http://localhost:5000"

Now replace all process.env.REACT_APP_BASE_URL with REACT_APP_BASE_URL.

The problem here was that the .env file in the frontend was not working for other users while it works for me.
So you have to do this in the frontend. After this the project will run smoothly if not then you can contact me.

**Comment by Yogndrr** [comment]
> Connected to MongoDB Server started at port no. 5000 NOT CONNECTED TO NETWORK MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
> 
> Here is the error I got

To fix this go to the backend, 
Create a file called .env in the backend folder.
Inside it write this :

MONGO_URL = mongodb://127.0.0.1/school

Instead of this link write your database link. 

Now in frontend go to src > redux > userRelated > userHandle.js

Write this after the import statements :

const REACT_APP_BASE_URL = "http://localhost:5000"

Now replace all process.env.REACT_APP_BASE_URL with REACT_APP_BASE_URL.

The problem here was that the .env file in the frontend was not working for other users while it works for me.
So you have to do this in the frontend. After this the project will run smoothly if not then you can contact me.

**Comment by Yogndrr** [comment]
Error fixed
